// Code generated by MockGen. DO NOT EDIT.
// Source: golang-payment-ledger/repository (interfaces: TransactionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/transaction.go golang-payment-ledger/repository TransactionRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-payment-ledger/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// ApplyTransfer mocks base method.
func (m *MockTransactionRepository) ApplyTransfer(ctx context.Context, params repository.ApplyTransferParams) (*repository.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTransfer", ctx, params)
	ret0, _ := ret[0].(*repository.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyTransfer indicates an expected call of ApplyTransfer.
func (mr *MockTransactionRepositoryMockRecorder) ApplyTransfer(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTransfer", reflect.TypeOf((*MockTransactionRepository)(nil).ApplyTransfer), ctx, params)
}
